export default {
  id: "hyperbolic",
  priority: 160,
  alias: "hyperbolic",
  aliases: [
    "hyp",
  ],
  uiAlias: "hyp",
  display: {
    name: "Hyperbolic",
    icon: "bolt",
    color: "#00D4FF",
    textIcon: "HY",
    website: "https://hyperbolic.xyz",
    notice: {
      apiKeyUrl: "https://app.hyperbolic.xyz/settings",
    },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://api.hyperbolic.xyz/v1/chat/completions",
    validateUrl: "https://api.hyperbolic.xyz/v1/models",
  },
  models: [
    { id: "Qwen/QwQ-32B", name: "QwQ 32B" },
    { id: "Qwen/Qwen3-Next-80B-A3B-Thinking", name: "Qwen3 Next 80B Thinking" },
    { id: "Qwen/Qwen3-Next-80B-A3B-Instruct", name: "Qwen3 Next 80B" },
    { id: "openai/gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "openai/gpt-oss-20b", name: "GPT OSS 20B" },
    { id: "deepseek-ai/DeepSeek-R1", name: "DeepSeek R1" },
    { id: "deepseek-ai/DeepSeek-V3", name: "DeepSeek V3" },
    { id: "meta-llama/Llama-3.3-70B-Instruct", name: "Llama 3.3 70B" },
    { id: "meta-llama/Llama-3.2-3B-Instruct", name: "Llama 3.2 3B" },
    { id: "meta-llama/Meta-Llama-3.1-405B", name: "Llama 3.1 405B" },
    { id: "Qwen/Qwen2.5-72B-Instruct", name: "Qwen 2.5 72B" },
    { id: "Qwen/Qwen2.5-Coder-32B-Instruct", name: "Qwen 2.5 Coder 32B" },
    { id: "NousResearch/Hermes-3-Llama-3.1-70B", name: "Hermes 3 70B" },
  ],
};
