export default {
  id: "perplexity-agent",
  priority: 181,
  alias: "perplexity-agent",
  aliases: [
    "pplx-agent",
    "pplx-responses",
  ],
  uiAlias: "pa",
  display: {
    name: "Perplexity Agent",
    icon: "travel_explore",
    color: "#20808D",
    textIcon: "PA",
    website: "https://www.perplexity.ai",
    notice: {
      text: "Perplexity Agent API exposes GPT, Claude, Gemini, Grok, GLM, Kimi, and Sonar models through one OpenAI-compatible Responses API.",
      apiKeyUrl: "https://www.perplexity.ai/settings/api",
    },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://api.perplexity.ai/v1/responses",
    validateUrl: "https://api.perplexity.ai/v1/models",
    format: "openai-responses",
  },
  models: [
    { id: "anthropic/claude-fable-5", name: "claude fable 5" },
    { id: "anthropic/claude-fable-5-1", name: "claude fable 5 1" },
    { id: "anthropic/claude-opus-5-5", name: "claude opus 5 5" },
    { id: "anthropic/claude-opus-5", name: "claude opus 5" },
    { id: "anthropic/claude-opus-4-7", name: "claude opus 4 7" },
    { id: "anthropic/claude-opus-4-6", name: "claude opus 4 6" },
    { id: "anthropic/claude-opus-4-5", name: "claude opus 4 5" },
    { id: "anthropic/claude-sonnet-5-5", name: "claude sonnet 5 5" },
    { id: "anthropic/claude-sonnet-5", name: "claude sonnet 5" },
    { id: "anthropic/claude-sonnet-4-5", name: "claude sonnet 4 5" },
    { id: "anthropic/claude-haiku-4-5", name: "claude haiku 4 5" },
    { id: "openai/gpt-6.1-sol", name: "gpt 6.1 sol" },
    { id: "openai/gpt-6-sol", name: "gpt 6 sol" },
    { id: "openai/gpt-6-luna", name: "gpt 6 luna" },
    { id: "openai/gpt-5.6-sol", name: "gpt 5.6 sol" },
    { id: "openai/gpt-5.6-terra", name: "gpt 5.6 terra" },
    { id: "openai/gpt-5.6-luna", name: "gpt 5.6 luna" },
    { id: "google/gemini-3.1-flash-lite", name: "gemini 3.1 flash lite" },
    { id: "google/gemini-3.5-flash", name: "gemini 3.5 flash" },
    { id: "google/gemini-3.5-flash-lite", name: "gemini 3.5 flash lite" },
    { id: "google/gemini-3.6-flash", name: "gemini 3.6 flash" },
    { id: "google/gemini-3.7-flash", name: "gemini 3.7 flash" },
    { id: "google/gemini-3.8-flash", name: "gemini 3.8 flash" },
    { id: "google/gemini-3-flash-preview", name: "gemini 3 flash preview" },
    { id: "xai/grok-4.7", name: "grok 4.7" },
    { id: "xai/grok-4.6", name: "grok 4.6" },
    { id: "xai/grok-4.5", name: "grok 4.5" },
    { id: "xai/grok-4.3", name: "grok 4.3" },
    { id: "xai/grok-4.20-non-reasoning", name: "grok 4.20 non reasoning" },
    { id: "xai/grok-4.20-multi-agent", name: "grok 4.20 multi agent" },
    { id: "perplexity/glm-5.3-flash", name: "GLM 5.3 flash" },
    { id: "perplexity/kimi-k3", name: "Kimi k3" },
    { id: "perplexity/sonar", name: "Perplexity Sonar" },
    { id: "openai/gpt-5.5", name: "GPT-5.5" },
    { id: "openai/gpt-5.4", name: "GPT-5.4" },
    { id: "openai/gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "anthropic/claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "anthropic/claude-opus-4-8", name: "Claude Opus 4.8" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro" },
    { id: "xai/grok-4.20-reasoning", name: "Grok 4.20 Reasoning" },
    { id: "perplexity/glm-5.3", name: "GLM 5.3" },
    { id: "perplexity/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "perplexity/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra 550B" },
  ],
  serviceKinds: ["llm", "webSearch"],
  searchViaChat: {
    defaultModel: "perplexity/sonar",
    endpoint: "https://api.perplexity.ai/v1/responses",
    pricingUrl: "https://docs.perplexity.ai/docs/agent-api/models",
  },
  modelsFetcher: { url: "https://api.perplexity.ai/v1/models", type: "openai" },
  passthroughModels: true,
};
