export default {
  id: "together",
  priority: 60,
  alias: "together",
  display: {
    name: "Together AI",
    icon: "group_work",
    color: "#0F6FFF",
    textIcon: "TG",
    website: "https://www.together.ai",
    notice: {
      apiKeyUrl: "https://api.together.xyz/settings/api-keys",
    },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://api.together.xyz/v1/chat/completions",
    validateUrl: "https://api.together.xyz/v1/models",
  },
  models: [
    { id: "meta-llama/Llama-3.3-70B-Instruct-Turbo", name: "Llama 3.3 70B Turbo" },
    { id: "deepseek-ai/DeepSeek-V4-Pro-0813", name: "DeepSeek V4 Pro" },
    { id: "deepseek-ai/DeepSeek-V4-Flash-0731", name: "DeepSeek V4 Flash" },
    { id: "deepseek-ai/DeepSeek-V4.1-Flash", name: "DeepSeek V4.1 Flash" },
    { id: "moonshotai/Kimi-K3", name: "Kimi K3" },
    { id: "zai-org/GLM-5.3", name: "GLM 5.3" },
    { id: "zai-org/GLM-5.3-Flash", name: "GLM 5.3 Flash" },
    { id: "zai-org/GLM-5.2", name: "GLM 5.2" },
    { id: "openai/gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "Qwen/Qwen3.8-Flash", name: "Qwen3.8 Flash" },
    { id: "Qwen/Qwen3.8-2.4T-A95B", name: "Qwen3.8 2.4T A95B" },
    { id: "Qwen/Qwen3.7-Max", name: "Qwen3.7 Max" },
    { id: "Qwen/Qwen3.7-Plus", name: "Qwen3.7 Plus" },
    { id: "Qwen/Qwen3.6-Plus", name: "Qwen3.6 Plus" },
    { id: "Qwen/Qwen3.5-9B", name: "Qwen3.5 9B" },
    { id: "MiniMaxAI/MiniMax-M3", name: "MiniMax M3" },
  ],
  serviceKinds: ["llm"],
  embeddingConfig: { baseUrl: "https://api.together.xyz/v1/embeddings" },
};
